/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.3.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as categorize from "../categorize.js";
import type * as helpers from "../helpers.js";
import type * as journal from "../journal.js";
import type * as notes from "../notes.js";
import type * as recordings from "../recordings.js";
import type * as reminders from "../reminders.js";
import type * as todoLists from "../todoLists.js";
import type * as transcript from "../transcript.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  categorize: typeof categorize;
  helpers: typeof helpers;
  journal: typeof journal;
  notes: typeof notes;
  recordings: typeof recordings;
  reminders: typeof reminders;
  todoLists: typeof todoLists;
  transcript: typeof transcript;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
